name: ethodrome tracker
description: Track flies in video. For more information see source code <https://github.com/janclemenslab/ethodrome>`_.
input:
  - video files (.mp4)
output:
  - tracks file (*_tracks.h5)