name: ethotracker
description: Track flies in video. For more information see source code https://github.com/janclemenslab/ethotracker.
input:
  - video files (mp4)
output:
  - tracks file (h5)
required_params:
  - profile
  - threshold