name: deepposekit
channels:
  - defaults
dependencies:
  - python=3.7
  - opencv
  - tensorflow-gpu=1.15
  - keras==2.2.4  # prevents import error in deepposekit
  - pandas
  - zarr
  - xarray
  - pip
  - git
  - pip:
    - xarray-behave
    - pyvideoreader
    - flammkuchen
    - git+https://github.com/janclemenslab/leap_utils   # leap-utils==0.1
    - git+https://github.com/jgraving/DeepPoseKit.git@v0.1.1.dev  # deepposekit==0.1.1.dev0
    # - git+https://github.com/janclemenslab/xarray-behave  # xarray-behave

