name: deepposekit
description: Track flies in video. For more information see http://deepposekit.org.
input:
  - video files (mp4)
  - ethotracker files (h5)
output:
  - pose tracks files (h5)
required_params:
  - modelname (produced by deepposekit )
help:
  - Expects `csv` file with skeleton information with the same basename as the model.