name: deepposekit
description: Track flies in video. For more information see http://deepposekit.org.
input:
  - video files (mp4)
  - ethotracker files (h5)
output:
  - pose tracks files (h5)
required_params:
  - tracksfilename (from ethotracker)
  - savename
  - modelname (produced by deepposekit )
help:
  - Expects `skeleton_initialized.csv` in the same folder as the model.